### PR TITLE
Added bin directory that contains scripts to build OVJ. Updated Readme

### PR DESCRIPTION
**Pull request by DanIverson**
The included scripts are buildovj, makeovj, and whatsin

### CODE REVIEW

**Comment by timburrow** [comment]
Do I need to update OpenVnmrj/OpenVnmrj to delete  the copied scripts? It'll be confusing to have 2 copies.

**Comment by DanIverson** [comment]
I was going to do that. I need practice doing simple things. I assume I should do it to the tim-developmen branch

**Comment by timburrow** [comment]
Yes. Please work in that branch. We'all need to test then pull across later.

**Comment by DanIverson** [comment]
I forked OpenVnmrJ to the daniverson account. On the Oregon machine, I did
git clone ssh://daniverson@github.com/daniverson/OpenVnmrj.git
cd OpenVnmrJ
git checkout tim-developmen
git rm src/scripts/buildovj  src/scripts/makeovj  src/scripts/whatsin.sh
git push

On the github site, I selected the daniverson/OpenVnmrJ repo and selected
the tim-developmen branch. I saw the update.  I then clicked the "New pull
request" button. Everything seemed to work. I saw one pull request for
OpenVnmrJ/OpenvnmrJ.  I then wanted to add some .gitignore files to
suppress build artifacts from showing when one does git status.
I used git add to add them and then git push. Again, they showed up on
github in daniverson/openvnmrj. I clicked the "New pull request" again but
when I went to OpenVnmrJ/OpenVnmrJ, there is only one pull request with
both commits in it. I has hoping for two pull requests, each with a single
commit. Any idea what I did wrong?

**Pull request merged**
