### PR TITLE
Development

### PR DESCRIPTION
**Pull request by tesch1**

### CODE REVIEW

**Comment by DanIverson** [comment]
A couple of items. This PR reverts some changes made by Tim to the makeovj and buildovj scripts. I believe those changes are required for the proper functioning of the build process. Also, when OpenVnmrJ was setup, the intention was for the copyright of all contributions to be assigned to the Univ. of Oregon ( @mstrain ). There was supposed to be a CLA signed by contributors. I don't know if @timburrow or @ekpaulson ever finalized this process.

**Comment by tesch1** [comment]
Thanks for looking at it.  Hope to address these items:

"This PR reverts some changes made by Tim to the makeovj and buildovj scripts."
That is not correct, not sure where that's coming from?  There are two edits to the existing build system, one to `bin/buildovj` -- that is just formatting of the comments to make the variable descriptions easier to read, and to `bin/whatis` -- that is to mark its output as coming from that script.  Neither are functional changes to that build process.  The rest of the changes are a build system that works seamlessly on VMs, and allows a complete rebuild on a clean reproducible VM for a number of different target configurations (CentOS{6,7},Ubuntu{14,16},MacOS).  This is a necessary step toward fully-automated build & test & packaging on all of those targets.

Regarding the CLA, I didn't remember anything about this on the website, so just dug into it now, and found one broken link to "How to Join.md" [here](http://openvnmrj.org/Contributing/#how-to-join-this-project) , and then had to dig into the repo for the docs to find this: https://github.com/OpenVnmrJ/Documentation/blob/master/How%20to%20Join.md and this: https://github.com/OpenVnmrJ/Documentation/blob/master/OpenVnmrJ%20CLA.md .. it's not clear if these are works-in-progress?

I can release my own work under Apache2.0 or GPL licenses.  I have been working under the assumption that I can contribute this way and that such contributions are welcome.

In the spirit of an open-source project, it would be great to put clearer information about the license situation on openvnmrj.org to make the path to productive contribution clear.

**Comment by DanIverson** [comment]
For the differences in buildovj and makeovj, I did the following:

git clone ssh://git@github.com/OpenVnmrJ/ovjTools.git
cd ovjTools
git checkout master
cp -r bin  bin.master
git checkout development
diff bin/buildovj  bin.master/buildovj

In addition to changes in the comments, it showed

  41a42,51
\>   timestamp=\`date +%s\`
\>   if [ -d "${ovjBuildDir}" ]; then
\>     touch "${ovjBuildDir}"/TESTFILE-$timestamp "${ovjBuildDir}"/testfile-$timestamp
\>     rm "${ovjBuildDir}"/TESTFILE-$timestamp
\>     if [ -f "${ovjBuildDir}"/testfile-$timestamp ]; then
\>       rm "${ovjBuildDir}"/testfile-$timestamp
\>     else 
\>       echo "Case insensitive file system. Watch out for biosolidspack experiments"
\>     fi
\>   fi
64c74
\< osxSDK='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSpreventX.platform/Developer/SDKs/MacOSX10.11.sdk'
\---
\> osxSDK='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk'

diff bin/makeovj  bin.master/makeovj

It showed,

  63,68c63,67
\< #   git checkout src
\<     echo "git fetch origin master"
\< #   git pull src
\<     git fetch origin master
\<     git checkout origin/master -- src
\<     git pull origin master # on CentOS's older git above doesn't work
\---
\>     git checkout src
\>     git pull 
\> #   git fetch origin master
\> #    git checkout origin/master -- src
\> #    git pull origin master # on CentOS's older git above doesn't work
 
(I added some backslashes to the diff output to suppress the github markdown formatting.)

It certainly seems that the CLA issue is not yet complete. I am hoping Tim or Erik or Mike will respond.  The goal is not to introduce obstacles, but, as you said, to make the path to productive contribution clear.

**Comment by timburrow** [comment]
In PR #20 the macOS naming was removed, with a comment it wasn't being used there

I thought the CLA-Assistant made it automatic to sign the CLA, but it's only set up for the appdirs repository.

**Comment by tesch1** [comment]
@DanIverson  It only looks like that because the development branch isn't up-to-date with the master branch.  Unless I'm horribly mistaken, merging this PR wont revert the changes erstwhile made to master.

To check that on the command line (it's also visible on this PR webpage in the "Files changed" tab up above), the process would be:
```
git clone ssh://git@github.com/OpenVnmrJ/ovjTools.git
cd ovjTools
cp -r bin bin.master
git merge development
diff bin bin.master
```
`master` is ahead of `development` because there were some commits merged directly from timburrow/master into the ovjTools/master instead of first into ovjTools/development (which it seems is contrary to the [stated best practice](http://openvnmrj.org/Contributing/#branch-information)? -- sorry to call you out on this @timburrow :)  Somebody should probably merge those changes back into development too: #22 .

**Pull request merged**
