### PR TITLE
Updates for VM build scripts.

### PR DESCRIPTION
**Pull request by tesch1**
- added script install_test.sh for gui-less install
- updates to install/test within VM functionality
- move install_test.sh to OpenVnmrJ repo.
- fixes for vm vjqa
- add an option to pass flags to install_test.sh (ie -F '-c inova')
- treat fedora like centos
- added some missing rpm packages for centos7
- moved logging stuff to loglib.sh shell-function library
- default log file name is now build_vm...log
- take ubuntu18 and macos10.10 out of 'all' target until they work
- catch a bunch of error conditions
- retrieve VJQA test result as log file named vjqa_....txt
- make sure vagrant setup scripts fail on error with set -e
- default the debian installations to use bash as /bin/sh (not dash!)
- started (an unfinished) 'package' option to build .rpm/.deb
- log runtimes of various build stages
- checkout less git depth for shallow builds
- use 4 cpus on VMs instead of 2 for faster build.
- make Vagrantfile installs fail if packages dont install

### CODE REVIEW

**Comment by DanIverson** [comment]
With PRs 159 and 210 in OpenVnmrJ, I removed the need to install the following packages.
 tcl.i686 tcl-devel.i686 tk.i686 tk-devel.i686 libtiff.i686 libtiff-devel.i686

**Comment by tesch1** [comment]
I'll remove those and test rebuilding on centos6&7 ubuntu14&16...

**Comment by tesch1** [comment]
I've removed the offenders and retested everything, looks good.

**Comment by tesch1** [comment]
still missing gsl libs on ubuntu..

**Comment by tesch1** [comment]
Ok, cleaned up the library situation, should be good to go.  Works for ubuntu14 ubuntu16, centos6, centos7.

**Pull request merged**
