### PR TITLE
Vagrant build cleanup

### PR DESCRIPTION
**Pull request by tesch1**
- Added an option to select the branch to be built
- Limit the git clone to depth of 3
- cleaned up package list for ubuntu14

### CODE REVIEW

**Comment by tesch1** [comment]
@timburrow , you mentioned there's a box available for testing.  Would you be interested to get this stuff setup for nightly (or even better: pull-request) builds?

What it does:
- creates vagrant "box" templates for the supported OSs
- for each build, clones the box, then downloads and runs the build in the VM

Both centos6 and trusty tahr are working, havent tried centos7 yet.

The install doesn't work yet, but it's close.

**Comment by tesch1** [comment]
Just cleaned up the commit history on this and added Xenial.

**Comment by osparking** [comment]
Thanks for fast response, sir.
I'm having hard time figuring out how to install JDK 6 which is an old version.
Do you know any link that leads to a page explaining how to install JDK 6 on Ubuntu?

**Comment by tesch1** [comment]
Is there a reason you're commenting on this merge request?

Are you trying to use the Vagrant builds on the development branch?  It would be better if you would open a new ticket with more information about the error you're getting.

**Pull request merged**
