### PR TITLE
Updated buildovj 

### PR DESCRIPTION
**Pull request by timburrow**
* checks for case sensitive file system
* does not specify SDK version

### CODE REVIEW

**Comment by DanIverson** [comment]
Do you think we need to abort the MacOS build if the file system is not case sensitive? The only files it affects are 1 imaging macro and a couple of biosolidspack experiments. The vast majority of people don't really care about those files. I asked the imaging people some time ago about tDELTA and they said it was not used. To rename the biosolidspack files we will need some input from Dave Rice. The file names, including capitalization, are actually based on a naming convention.

**Comment by timburrow** [comment]
I was more afraid of the .C files, whether they'd be compiled as C++ or just C. Maybe I could check if that is truly an issue because OS X is case preserving. Are you using a case-sensitive file system on the mac?

We should ask Dave Rice to rename the biosolidspack experiments, maybe with underscores instead of caps. I just don't want to blow away experiments accidentally.

**Comment by DanIverson** [comment]
I am using a case insensitive file system and do not have a problem with .C files. They are compiled correctly.
I will check with Dave about the biosolidspack files.

**Comment by timburrow** [comment]
These are the case sensitive files:
find . -type d -exec sh -c "find {} -maxdepth 1 | sort -f | uniq -di" \; 
./src/IMAGE/imaging/maclib/_tDELTA
./src/biosolidspack/maclib/CAncoCX2dSCANS
./src/biosolidspack/maclib/COncaCX2dSCANS
./src/biosolidspack/maclib/NcaCX2dSCANS
./src/biosolidspack/maclib/NcoCX2dSCANS
./src/biosolidspack/templates/vnmrj/protocols/CAncoCX2dSCANS.xml
./src/biosolidspack/templates/vnmrj/protocols/COncaCX2dSCANS.xml
./src/biosolidspack/templates/vnmrj/protocols/NcaCX2dSCANS.xml
./src/biosolidspack/templates/vnmrj/protocols/NcoCX2dSCANS.xml

Not an issue, so I’ll put a warning until the biosolidspack files are renamed

**Comment by timburrow** [comment]
Proposal for renaming 8 biosolidspack sequences

CAncoCX2dSCANS => CA_ncoCX2dSCANS
caNcoCX2dSCANS => ca_N_coCX2dSCANS

COncaCX2dSCANS => CO_ncaCX2dSCANS
coNcaCX2dSCANS => co_N_caCX2dSCANS

NcaCX2dSCANS => N_caCX2dSCANS
nCACX2dSCANS => n_CA_CX2dSCANS

NcoCX2dSCANS => N_coCX2dSCANS
nCOCX2dSCANS => n_CO_CX2dSCANS

**Pull request merged**
